### PR TITLE
CM-209 Backend: ABMC operaciones

### PR DESCRIPTION
**Pull request by merlindk**

### CODE REVIEW

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
add to whitelist

**Comment by merlindk** [comment]
ok to test

**Comment by merlindk** [comment]
test this please

**Comment by merlindk** [comment]
test this please

**Review by FranciscodeMaussion — APPROVED** [review]

**Pull request merged**
